# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/nikhil/SemV/CSP301/Project/FinalGame

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/nikhil/SemV/CSP301/Project/FinalGame

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nikhil/SemV/CSP301/Project/FinalGame/CMakeFiles /home/nikhil/SemV/CSP301/Project/FinalGame/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/nikhil/SemV/CSP301/Project/FinalGame/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named Game

# Build rule for target.
Game: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 Game
.PHONY : Game

# fast build rule for target.
Game/fast:
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/build
.PHONY : Game/fast

# target to build an object file
Chance.o:
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Chance.o
.PHONY : Chance.o

# target to preprocess a source file
Chance.i:
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Chance.i
.PHONY : Chance.i

# target to generate assembly for a file
Chance.s:
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Chance.s
.PHONY : Chance.s

# target to build an object file
Chest.o:
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Chest.o
.PHONY : Chest.o

# target to preprocess a source file
Chest.i:
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Chest.i
.PHONY : Chest.i

# target to generate assembly for a file
Chest.s:
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Chest.s
.PHONY : Chest.s

# target to build an object file
Player.o:
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Player.o
.PHONY : Player.o

# target to preprocess a source file
Player.i:
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Player.i
.PHONY : Player.i

# target to generate assembly for a file
Player.s:
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Player.s
.PHONY : Player.s

# target to build an object file
Properties.o:
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Properties.o
.PHONY : Properties.o

# target to preprocess a source file
Properties.i:
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Properties.i
.PHONY : Properties.i

# target to generate assembly for a file
Properties.s:
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/Properties.s
.PHONY : Properties.s

# target to build an object file
botPlayer.o:
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/botPlayer.o
.PHONY : botPlayer.o

# target to preprocess a source file
botPlayer.i:
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/botPlayer.i
.PHONY : botPlayer.i

# target to generate assembly for a file
botPlayer.s:
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/botPlayer.s
.PHONY : botPlayer.s

# target to build an object file
main.o:
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/main.o
.PHONY : main.o

# target to preprocess a source file
main.i:
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/main.i
.PHONY : main.i

# target to generate assembly for a file
main.s:
	$(MAKE) -f CMakeFiles/Game.dir/build.make CMakeFiles/Game.dir/main.s
.PHONY : main.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... Game"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... Chance.o"
	@echo "... Chance.i"
	@echo "... Chance.s"
	@echo "... Chest.o"
	@echo "... Chest.i"
	@echo "... Chest.s"
	@echo "... Player.o"
	@echo "... Player.i"
	@echo "... Player.s"
	@echo "... Properties.o"
	@echo "... Properties.i"
	@echo "... Properties.s"
	@echo "... botPlayer.o"
	@echo "... botPlayer.i"
	@echo "... botPlayer.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

